spring:
  application:
    name: register_customer

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    password: password
    username: root
    url: jdbc:mysql://localhost:8089/mysql-transfer-db
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

secret:
  key: RmRfZ296bGVpcm5fbmVfZGV5aXJfYmFzYV9kdXN1cmVtX25peWVfY2FzZGlyaXJzYW5fZGlsaW5sZV9tZW5pX1Nh
services:
  akart:
    url: http://localhost:8082/v1/api
    username: Saida
    password: password123
logging:
  level:
    com.saida.register_customer: DEBUG